version: "3.9"
services:
  web:
    container_name: node-app
    build:
      context: .
      target: production
    command: npm start
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    env_file:
    - web-variables.env
    networks:
      - app-network
    volumes:
      - ~/node_app/web-root/snippet-app/src:/app/src
    restart: unless-stopped
  
  mongo:
    image: lemunter/1dv023_mongodb:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/node_app/mongoDB/database:/data/db
    networks:
      - app-network
    restart: unless-stopped

  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/node_app/web-root:/var/www/html
      - ~/node_app/nginx-conf:/etc/nginx/conf.d
      - ~/node_app/certbot-etc:/etc/letsencrypt
      - ~/node_app/certbot-var:/var/lib/letsencrypt
      - ~/node_app/dhparam:/etc/ssl/certs
    depends_on:
      - web
    networks:
      - app-network

  redis:
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    image: 'redis'

volumes:
  mongodb_data:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ~/node_app/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ~/node_app/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
